-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 11:56:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema ippl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ippl
-- -----------------------------------------------------
CREATE DATABASE ippl ;
USE ippl ;

-- -----------------------------------------------------
-- Table `ippl`.`alternatif`
-- -----------------------------------------------------
CREATE TABLE ippl.alternatif (
  id INT NOT NULL,
  nama VARCHAR(45) NOT NULL,
  kriteria1 FLOAT NOT NULL,
  kriteria2 FLOAT NOT NULL,
  kriteria3 FLOAT NOT NULL,
  kriteria4 FLOAT NOT NULL,
  kriteria5 FLOAT NOT NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table `ippl`.`kriteria`
-- -----------------------------------------------------
CREATE TABLE ippl.kriteria (
  id INT NOT NULL,
  kriteria1 FLOAT NOT NULL,
  kriteria2 FLOAT NOT NULL,
  kriteria3 FLOAT NOT NULL,
  kriteria4 FLOAT NOT NULL,
  kriteria5 FLOAT NOT NULL,
  PRIMARY KEY (id));

INSERT INTO kriteria(kriteria1,kriteria2,kriteria3,kriteria4,kriteria5) VALUES
(75,86,65,78,86);

INSERT INTO alternatif(nama,kriteria1,kriteria2,kriteria3,kriteria4,kriteria5) VALUES
("Nina",76.8,65.6,86.5,77.4,83.5),
("Siti",80.8,74.6,71.5,90.4,80.5),
("Mamat",60.8,70.6,68.5,76.4,68.5),
("Toni",75.8,90.6,85.5,90.4,87.5),
("Jajang",80.8,63.6,73.5,75.4,78.5);